#levels=c(15,31,56,103,121,122), labels=c("OSU","UPMC","PSU_HERSHEY","WAYNE_STATE","SGH","OSUHE")
sanitizer2<-function(x){
  meta_data<-x
  meta_data<-as.matrix(meta_data)
  meta_data<-as.data.frame(meta_data)
  meta_data$Site.x<-factor(meta_data$Site.x,levels=c(15,31,56,103,121,122), labels=c("OSU","UPMC","PSU_HERSHEY","WAYNE_STATE","SGH","OSUHE"))
  meta_data$Age<-as.numeric(meta_data$Age)
  meta_data$Sex<-factor(meta_data$Sex, levels=c(1,2),labels=c("Male","Female"))
  meta_data$Race<-factor(meta_data$Race, levels=c(1,2,3),labels=c("White","African Amer.","Other"))
  meta_data$CCI<-as.numeric(meta_data$CCI)
  meta_data$COPD_Hx<-factor(meta_data$COPD_Hx, levels=c("2","1","."),labels=c("No","Yes","Missing"))
  meta_data$Asthma_Hx<-factor(meta_data$Asthma_Hx, levels=c("2","1","."), labels=c("No","Yes","Missing"))
  meta_data$Current_Smoker<-factor(meta_data$Current_Smoker, levels=c("2","1",".","3"), labels=c("No","Yes","Unknown","Unknown"))
  meta_data$Past_Smoker<-factor(meta_data$Past_Smoker, levels=c("2","1","3","."),labels=c("No","Yes","Unknown","Unknown"))
  meta_data$HomeOxygen<-factor(meta_data$HomeOxygen, levels=c("2","1","."),labels=c("No","Yes","Unknown"))
  meta_data$CorticosteroidsOral<-factor(meta_data$CorticosteroidsOral, levels=c("2","1","."), labels=c("No","Yes","Unknown"))
  meta_data$Bronhciodilators<-factor(meta_data$Bronhciodilators, levels=c("2","1","."), labels=c("No","Yes","Unknown"))
  meta_data$LeukotrieneReceptorAntagonists<-factor(meta_data$LeukotrieneReceptorAntagonists, levels=c("2","1","."), labels=c("No","Yes","Unknown"))
  meta_data$EMS_steroids<-factor(meta_data$EMS_steroids, levels=c("2","1","."),labels=c("No","Yes","No EMS"))
  meta_data$EMS_bronchodilators<-factor(meta_data$EMS_bronchodilators, levels=c("2","1","."),labels=c("No","Yes","No EMS"))
  meta_data$In.hospital_Steroids<-factor(meta_data$In.hospital_Steroids, levels=c("2","1","."), labels=c("No","Yes","Not In hospital"))
  meta_data$In.hospital_Bronchodilators<-factor(meta_data$In.hospital_Bronchodilators, levels=c("2","1","."), labels=c("No","Yes","Not In hospital"))
  meta_data$Re_hosp_Steroids<-factor(meta_data$Re_hosp_Steroids, levels=c("2","1","."),labels=c("No","Yes","Not Rehospitalized"))
  meta_data$Re_hosp_Bronchodilators<-factor(meta_data$Re_hosp_Bronchodilators, levels=c("2","1","."), labels=c("No","Yes","Not Rehospitalized"))
  meta_data$Obs<-as.numeric(meta_data$Obs)
  meta_data$all_duration<-as.numeric(meta_data$all_duration)
  meta_data$Rhonchi<-factor(meta_data$Rhonchi, levels=c("2","1"),labels=c("No","Yes"))
  meta_data$Wheezing<-factor(meta_data$Wheezing, levels=c("2","1","."), labels=c("No","Yes","Unknown"))
  meta_data$Cough<-factor(meta_data$Cough, levels=c("2","1","."),labels=c("No","Yes","Unknown"))
  meta_data$Chills<-factor(meta_data$Chills, levels=c("2","1","."),labels=c("No","Yes","Unknown"))
  meta_data$Sputum<-factor(meta_data$Sputum, levels=c("2","1","."),labels=c("No","Yes","Unknown"))
  meta_data$Dyspnea<-factor(meta_data$Dyspnea, levels=c("2","1","."),labels=c("No","Yes","Unknown"))
  meta_data$Chest_Discomfort<-factor(meta_data$Chest_Discomfort, levels=c("2","1","."),labels=c("No","Yes","Unknown"))
  meta_data$Heartrate<-as.numeric(meta_data$Heartrate)
  meta_data$Resprate<-as.numeric(meta_data$Resprate)
  meta_data$MAP.<-as.numeric(meta_data$MAP.)
  meta_data$Temperature<-as.numeric(meta_data$Temperature)
  meta_data$OxygenSat<-as.numeric(meta_data$OxygenSat)
  meta_data$los<-as.numeric(meta_data$los)
  meta_data$OUTCOME_CAP<-factor(meta_data$OUTCOME_CAP, levels=c("n","y","."),labels=c("No","Yes","Unknown"))
  meta_data$OUTCOME_HCAP<-factor(meta_data$OUTCOME_HCAP, levels=c("n","y","."),labels=c("No","Yes","Unknown"))
  meta_data$OUTCOME_PSI<-factor(meta_data$OUTCOME_PSI, levels=c("1","2","3","4","."),labels=c("1","2","3","4","Unknown"))
  meta_data$OUTCOME_COPD<-factor(meta_data$OUTCOME_COPD, levels=c("n","y","."),labels=c("No","Yes","Unknown"))
  meta_data$OUTCOME_Asthma<-factor(meta_data$OUTCOME_Asthma, levels=c("n","y","."),labels=c("No","Yes","Unknown"))
  meta_data$OUTCOME_Acute_Bronchitis<-factor(meta_data$OUTCOME_Acute_Bronchitis, levels=c("n","y","."),labels=c("No","Yes","Unknown"))
  meta_data$OUTCOME_Other.<-factor(meta_data$OUTCOME_Other., levels=c("n","y","."),labels=c("No","Yes","Unknown"))
  meta_data$Overall_Adverse_outcome<-factor(meta_data$Overall_Adverse_outcome, levels=c("n","y","."),labels=c("No","Yes","Unknown"))
  meta_data$Adverse_outcome_Death<-factor(meta_data$Adverse_outcome_Death, levels=c("n","y","."),labels=c("No","Yes","Unknown"))
  meta_data$Adverse_outcome_Endotracheal_Intubation<-factor(meta_data$Adverse_outcome_Endotracheal_Intubation, levels=c("n","y","."),labels=c("No","Yes","Unknown"))
  meta_data$Adverse_outcome_Vasopressors<-factor(meta_data$Adverse_outcome_Vasopressors, levels=c("n","y","."),labels=c("No","Yes","Unknown"))
  meta_data$Adverse_outcome_Renal_Failure<-factor(meta_data$Adverse_outcome_Renal_Failure, levels=c("n","y","."),labels=c("No","Yes","Unknown"))
  meta_data$Adverse_outcome_Lungabscess_Emphysema<-factor(meta_data$Adverse_outcome_Lungabscess_Emphysema, levels=c("n","y","."),labels=c("No","Yes","Unknown"))
  meta_data$Adverse_outcome_Rehospitalization<-factor(meta_data$Adverse_outcome_Rehospitalization, levels=c("n","y","."),labels=c("No","Yes","Unknown"))
  meta_data$Day_15_f_u_status<-factor(meta_data$Day_15_f_u_status)
  meta_data$day_15_AQ20_score<-as.numeric(meta_data$day_15_AQ20_score)
  meta_data$Day.30_f_u_satus<-as.numeric(meta_data$Day.30_f_u_satus)
  meta_data$Day.30_AQ20_score<-as.numeric(meta_data$Day.30_AQ20_score)
  meta_data$Hospital_d_c_Dispostion<-factor(meta_data$Hospital_d_c_Dispostion)
  meta_data$receive_abx<-factor(meta_data$receive_abx, levels=c("0","1"), labels=c("No","Yes"))
  meta_data$abx_ed<-factor(meta_data$abx_ed, levels=c("0","1"), labels=c("No","Yes"))
  meta_data$hosp_admit<-factor(meta_data$hosp_admit)
  meta_data$Day_15_f_u_status<-as.numeric(meta_data$Day_15_f_u_status)
  meta_data$sum_inhosp_duration<-as.numeric(meta_data$sum_inhosp_duration)
  meta_data$Adverse_outcome_Pneumonia_in_non_cap<-factor(meta_data$Adverse_outcome_Pneumonia_in_non_cap, levels=c("n","y"), labels=c("No","Yes"))
  meta_data$Hospital_d_c_date<-as.numeric(meta_data$Hospital_d_c_date)
  meta_data$sum_rehosp_duration<-as.numeric(meta_data$sum_rehosp_duration)
  meta_data$ED_steroids<-factor(meta_data$ED_steroids, levels=c("2","1","."), labels=c("No","Yes","Unknown"))
  meta_data$ED_bronchodilators<-factor(meta_data$ED_bronchodilators, levels=c("2","1","."), labels=c("No","Yes","Unknown"))
  meta_data$Corticosteroidsinhaled<-factor(meta_data$Corticosteroidsinhaled, levels=c("2","1","."), labels=c("No","Yes","Unknown"))
  #meta_data$receive_abx<-as.character(meta_data$receive_abx)
  #meta_data$receive_abx<-factor(meta_data$receive_abx, levels=c(" 0"," 1"),labels=c("No","Yes"))
  #meta_data$abx_ed<-as.character(meta_data$abx_ed)
  #meta_data$abx_ed<-factor(meta_data$abx_ed, levels=c(" 0"," 1"),labels=c("No","Yes"))
  #meta_data$hosp_admit<-factor(meta_data$hosp_admit, levels=c("2","1"),labels=c("No","Yes"))
  #meta_data$receive_abx<-factor(meta_data$receive_abx, levels=c("0","1"), labels=c("No","Yes"),exclude=NA)
  meta_data$city<-factor(meta_data$city, levels=c("15","31","56","103","121","122"),labels=c("Columbus","Pittsburgh","Hershey","Detroit","Detroit","Columbus"))
  #meta_data$abx_ed<-factor(meta_data$abx_ed, levels=c("0","1"), labels=c("No","Yes"),exclude=NA)
  return(meta_data)
}

sparserFactors2<-function(x){
  metadata<-x
  metadata<-metadata[,-c(1:10,49)]
  Factorcols<-sapply(metadata, function(col) is.factor(col))
  tmp<-metadata[,Factorcols]
  removesparse<-as.vector("")
  for (i in 1:dim(tmp)[2]){
    print(colnames(tmp)[i])
    j<-table(tmp[,i])
    j<-j[j>1]
    if (length(j)==1){
      removesparse[i]<-FALSE} else{
        removesparse[i]<-TRUE}
  }
  removesparse<-as.logical(removesparse)
  tmp2<-tmp[,removesparse]
  j<-apply(tmp2,2,function(x) sum(is.na(x)/nrow(tmp))>0.85)
  tmp2<-tmp2[,!j]
  return(tmp2) 
}

sanitizer3<-function(x){
  meta_data<-x
  meta_data$Site.x<-factor(meta_data$Site.x,levels=c(15,31,56,103,121,122), labels=c("OSU","UPMC","PSU_HERSHEY","WAYNE_STATE","SGH","OSUHE"))
  meta_data$Age<-as.numeric(meta_data$Age)
  meta_data$Sex<-factor(meta_data$Sex, levels=c(1,2),labels=c("Male","Female"))
  meta_data$Race<-factor(meta_data$Race, levels=c("White","African American","3"),labels=c("White","African Amer.","White"))
  meta_data$CCI<-as.numeric(meta_data$CCI)
  meta_data$COPD_Hx<-factor(meta_data$COPD_Hx, levels=c("2","1"),labels=c("No","Yes"))
  meta_data$Asthma_Hx<-factor(meta_data$Asthma_Hx, levels=c("2","1"), labels=c("No","Yes"))
  meta_data$Current_Smoker<-factor(meta_data$Current_Smoker, levels=c("2","1",".","3"), labels=c("No","Yes","Unknown","Unknown"))
  meta_data$Past_Smoker<-factor(meta_data$Past_Smoker, levels=c("2","1","3","."),labels=c("No","Yes","Unknown","Unknown"))
  meta_data$HomeOxygen<-factor(meta_data$HomeOxygen, levels=c("2","1"),labels=c("No","Yes"))
  meta_data$CorticosteroidsOral<-factor(meta_data$CorticosteroidsOral, levels=c("2","1"), labels=c("No","Yes"))
  meta_data$Bronhciodilators<-factor(meta_data$Bronhciodilators, levels=c("2","1"), labels=c("No","Yes"))
  meta_data$LeukotrieneReceptorAntagonists<-factor(meta_data$LeukotrieneReceptorAntagonists, levels=c("2","1"), labels=c("No","Yes"))
  meta_data$EMS_steroids<-factor(meta_data$EMS_steroids, levels=c("2","1","."),labels=c("No","Yes","NA EMS"))
  meta_data$EMS_bronchodilators<-factor(meta_data$EMS_bronchodilators, levels=c("2","1","."),labels=c("No","Yes","NA EMS"))
  meta_data$In.hospital_Steroids<-factor(meta_data$In.hospital_Steroids, levels=c("2","1","."), labels=c("No","Yes","NA admitted"))
  meta_data$In.hospital_Bronchodilators<-factor(meta_data$In.hospital_Bronchodilators, levels=c("2","1","."), labels=c("No","Yes","NA admitted"))
  meta_data$Re_hosp_Steroids<-factor(meta_data$Re_hosp_Steroids, levels=c("2","1","."),labels=c("No","Yes","NA rehospitalized"))
  meta_data$Re_hosp_Bronchodilators<-factor(meta_data$Re_hosp_Bronchodilators, levels=c("2","1","."), labels=c("No","Yes","NA rehospitalized"))
  meta_data$Obs<-as.numeric(meta_data$Obs)
  meta_data$all_duration<-as.numeric(meta_data$all_duration)
  meta_data$Rhonchi<-factor(meta_data$Rhonchi, levels=c("2","1"),labels=c("No","Yes"))
  meta_data$Wheezing<-factor(meta_data$Wheezing, levels=c("2","1"), labels=c("No","Yes"))
  meta_data$Cough<-factor(meta_data$Cough, levels=c("2","1"),labels=c("No","Yes"))
  meta_data$Chills<-factor(meta_data$Chills, levels=c("2","1"),labels=c("No","Yes"))
  meta_data$Sputum<-factor(meta_data$Sputum, levels=c("2","1"),labels=c("No","Yes"))
  meta_data$Dyspnea<-factor(meta_data$Dyspnea, levels=c("2","1"),labels=c("No","Yes"))
  meta_data$Chest_Discomfort<-factor(meta_data$Chest_Discomfort, levels=c("2","1"),labels=c("No","Yes"))
  meta_data$Heartrate<-as.numeric(meta_data$Heartrate)
  meta_data$Resprate<-as.numeric(meta_data$Resprate)
  meta_data$MAP.<-as.numeric(meta_data$MAP.)
  meta_data$Temperature<-as.numeric(meta_data$Temperature)
  meta_data$OxygenSat<-as.numeric(meta_data$OxygenSat)
  meta_data$los<-as.numeric(meta_data$los)
  meta_data$OUTCOME_CAP<-factor(meta_data$OUTCOME_CAP, levels=c("n","y","."),labels=c("No","Yes","No"))
  meta_data$OUTCOME_HCAP<-factor(meta_data$OUTCOME_HCAP, levels=c("n","y","."),labels=c("No","Yes","Unknown"))
  meta_data$OUTCOME_PSI<-factor(meta_data$OUTCOME_PSI, levels=c(".","1","2","3","4"),labels=c("Unknown","1","2","3","4"))
  meta_data$OUTCOME_COPD<-factor(meta_data$OUTCOME_COPD, levels=c("n","y","."),labels=c("No","Yes","No"))
  meta_data$OUTCOME_Asthma<-factor(meta_data$OUTCOME_Asthma, levels=c("n","y","."),labels=c("No","Yes","No"))
  meta_data$OUTCOME_Acute_Bronchitis<-factor(meta_data$OUTCOME_Acute_Bronchitis, levels=c("n","y","."),labels=c("No","Yes","No"))
  meta_data$OUTCOME_Other.<-factor(meta_data$OUTCOME_Other., levels=c("n","y","."),labels=c("No","Yes","Unknown"))
  meta_data$Overall_Adverse_outcome<-factor(meta_data$Overall_Adverse_outcome, levels=c("n","y","."),labels=c("No","Yes","Unknown"))
  meta_data$Adverse_outcome_Death<-factor(meta_data$Adverse_outcome_Death, levels=c("n","y","."),labels=c("No","Yes","Unknown"))
  meta_data$Adverse_outcome_Endotracheal_Intubation<-factor(meta_data$Adverse_outcome_Endotracheal_Intubation, levels=c("n","y"),labels=c("No","Yes"))
  meta_data$Adverse_outcome_Vasopressors<-factor(meta_data$Adverse_outcome_Vasopressors, levels=c("n","y"),labels=c("No","Yes"))
  meta_data$Adverse_outcome_Renal_Failure<-factor(meta_data$Adverse_outcome_Renal_Failure, levels=c("n","y"),labels=c("No","Yes"))
  meta_data$Adverse_outcome_Lungabscess_Emphysema<-factor(meta_data$Adverse_outcome_Lungabscess_Emphysema, levels=c("n","y","."),labels=c("No","Yes","Unknown"))
  meta_data$Adverse_outcome_Rehospitalization<-factor(meta_data$Adverse_outcome_Rehospitalization, levels=c("n","y","."),labels=c("No","Yes","Unknown"))
  meta_data$Day_15_f_u_status<-factor(meta_data$Day_15_f_u_status)
  meta_data$day_15_AQ20_score<-as.numeric(meta_data$day_15_AQ20_score)
  meta_data$Day.30_f_u_satus<-as.numeric(meta_data$Day.30_f_u_satus)
  meta_data$Day.30_AQ20_score<-as.numeric(meta_data$Day.30_AQ20_score)
  meta_data$Hospital_d_c_Dispostion<-factor(meta_data$Hospital_d_c_Dispostion)
  #meta_data$receive_abx<-factor(meta_data$receive_abx, levels=c(0,1), labels=c("No","Yes"))
  meta_data$Day_15_f_u_status<-as.numeric(meta_data$Day_15_f_u_status)
  meta_data$sum_inhosp_duration<-as.numeric(meta_data$sum_inhosp_duration)
  meta_data$Adverse_outcome_Pneumonia_in_non_cap<-factor(meta_data$Adverse_outcome_Pneumonia_in_non_cap, levels=c("n","y"), labels=c("No","Yes"))
  meta_data$Hospital_d_c_date<-as.numeric(meta_data$Hospital_d_c_date)
  meta_data$sum_rehosp_duration<-as.numeric(meta_data$sum_rehosp_duration)
  meta_data$ED_steroids<-factor(meta_data$ED_steroids, levels=c("2","1","."), labels=c("No","Yes","NA in ED"))
  meta_data$ED_bronchodilators<-factor(meta_data$ED_bronchodilators, levels=c("2","1","."), labels=c("No","Yes","NA in ED"))
  meta_data$Corticosteroidsinhaled<-factor(meta_data$Corticosteroidsinhaled, levels=c("2","1"), labels=c("No","Yes"))
  meta_data$receive_abx<-gsub(0, "No",meta_data$receive_abx)
  meta_data$receive_abx<-gsub(1, "Yes",meta_data$receive_abx)
  meta_data$receive_abx<-factor(meta_data$receive_abx, levels=c("No","Yes"),labels=c("No","Yes"))
  #meta_data$receive_abx<-factor(meta_data$receive_abx, levels=c("No","Yes"),labels=c("No","Yes"))
  meta_data$abx_ed<-gsub(0,"No",meta_data$abx_ed)
  meta_data$abx_ed<-gsub(1,"Yes",meta_data$abx_ed)
  meta_data$abx_ed<-factor(meta_data$abx_ed, levels=c("No","Yes"),labels=c("No","Yes"))
  #meta_data$abx_ed<-factor(meta_data$abx_ed, levels=c("No","Yes"),labels=c("No","Yes"))
  meta_data$hosp_admit<-gsub(2,"No",meta_data$hosp_admit)
  meta_data$hosp_admit<-gsub(1,"Yes",meta_data$hosp_admit)
  meta_data$hosp_admit<-factor(meta_data$hosp_admit, levels=c("No","Yes",NA),labels=c("No","Yes"),exclude=NA)
  #meta_data$receive_abx<-factor(meta_data$receive_abx, levels=c("0","1"), labels=c("No","Yes"))
  #meta_data$abx_ed<-factor(meta_data$abx_ed, levels=c("0","1"), labels=c("No","Yes"),exclude=NA)
  meta_data$LRTIdecision<-factor(meta_data$LRTIdecision, levels=c("n","y"), labels=c("No","Yes"))
  meta_data$city<-factor(meta_data$city, levels=c("15","31","56","103","121","122"),labels=c("Columbus","Pittsburgh","Hershey","Detroit","Detroit","Columbus"))
  return(meta_data)
}

#levels=c(15,31,56,103,121,122), labels=c("OSU","UPMC","PSU_HERSHEY","WAYNE_STATE","SGH","OSUHE")
sanitizerReference<-function(x){
  meta_data<-meta(x)
  meta_data<-as.data.frame(meta_data)
  Refsamples<-grep('ASAL',meta_data$Sample_ID)
  meta_data[Refsamples,c(4:80)]<-"Reference"
  meta_data[Refsamples,48]<-"1"
  meta_data$Site.x<-factor(meta_data$Site.x,levels=c(15,31,56,103,121,122,"Reference"), labels=c("OSU","UPMC","PSU_HERSHEY","WAYNE_STATE","SGH","OSUHE","Reference"))
  meta_data$Age<-as.numeric(meta_data$Age)
  meta_data$Sex<-factor(meta_data$Sex, levels=c(1,2,"Reference"),labels=c("No","Yes","Reference"))
  meta_data$Race<-factor(meta_data$Race, levels=c(1,2,3,"Reference"),labels=c("No","Yes","Yes","Reference"))
  meta_data$CCI<-as.numeric(meta_data$CCI)
  meta_data$COPD_Hx<-factor(meta_data$COPD_Hx, levels=c("2","1","Reference"),labels=c("No","Yes","Reference"))
  meta_data$Asthma_Hx<-factor(meta_data$Asthma_Hx, levels=c("2","1","Reference"), labels=c("No","Yes","Reference"))
  meta_data$Current_Smoker<-factor(meta_data$Current_Smoker, levels=c("2","1",".","3","Reference"), labels=c("No","Yes","Unknown","Unknown","Reference"))
  meta_data$Past_Smoker<-factor(meta_data$Past_Smoker, levels=c("2","1","3",".","Reference"),labels=c("No","Yes","Unknown","Unknown","Reference"))
  meta_data$HomeOxygen<-factor(meta_data$HomeOxygen, levels=c("2","1","Reference"),labels=c("No","Yes","Reference"))
  meta_data$CorticosteroidsOral<-factor(meta_data$CorticosteroidsOral, levels=c("2","1","Reference"), labels=c("No","Yes","Reference"))
  meta_data$Bronhciodilators<-factor(meta_data$Bronhciodilators, levels=c("2","1","Reference"), labels=c("No","Yes","Reference"))
  meta_data$LeukotrieneReceptorAntagonists<-factor(meta_data$LeukotrieneReceptorAntagonists, levels=c("2","1","Reference"), labels=c("No","Yes","Reference"))
  meta_data$EMS_steroids<-factor(meta_data$EMS_steroids, levels=c("2","1",".","Reference"),labels=c("No","Yes","No EMS","Reference"))
  meta_data$EMS_bronchodilators<-factor(meta_data$EMS_bronchodilators, levels=c("2","1",".","Reference"),labels=c("No","Yes","No EMS","Reference"))
  meta_data$In.hospital_Steroids<-factor(meta_data$In.hospital_Steroids, levels=c("2","1",".","Reference"), labels=c("No","Yes","Not admitted","Reference"))
  meta_data$In.hospital_Bronchodilators<-factor(meta_data$In.hospital_Bronchodilators, levels=c("2","1",".","Reference"), labels=c("No","Yes","Not admitted","Reference"))
  meta_data$Re_hosp_Steroids<-factor(meta_data$Re_hosp_Steroids, levels=c("2","1",".","Reference"),labels=c("No","Yes","Not rehospitalized","Reference"))
  meta_data$Re_hosp_Bronchodilators<-factor(meta_data$Re_hosp_Bronchodilators, levels=c("2","1",".","Reference"), labels=c("No","Yes","Not rehospitalized","Reference"))
  meta_data$Obs<-as.numeric(meta_data$Obs)
  meta_data$all_duration<-as.numeric(meta_data$all_duration)
  meta_data$Rhonchi<-factor(meta_data$Rhonchi, levels=c("2","1","Reference"),labels=c("No","Yes","Reference"))
  meta_data$Wheezing<-factor(meta_data$Wheezing, levels=c("2","1","Reference"), labels=c("No","Yes","Reference"))
  meta_data$Cough<-factor(meta_data$Cough, levels=c("2","1","Reference"),labels=c("No","Yes","Reference"))
  meta_data$Chills<-factor(meta_data$Chills, levels=c("2","1","Reference"),labels=c("No","Yes","Reference"))
  meta_data$Sputum<-factor(meta_data$Sputum, levels=c("2","1","Reference"),labels=c("No","Yes","Reference"))
  meta_data$Dyspnea<-factor(meta_data$Dyspnea, levels=c("2","1","Reference"),labels=c("No","Yes","Reference"))
  meta_data$Chest_Discomfort<-factor(meta_data$Chest_Discomfort, levels=c("2","1","Reference"),labels=c("No","Yes","Reference"))
  meta_data$Heartrate<-as.numeric(meta_data$Heartrate)
  meta_data$Resprate<-as.numeric(meta_data$Resprate)
  meta_data$MAP.<-as.numeric(meta_data$MAP.)
  meta_data$Temperature<-as.numeric(meta_data$Temperature)
  meta_data$OxygenSat<-as.numeric(meta_data$OxygenSat)
  meta_data$los<-as.numeric(meta_data$los)
  meta_data$OUTCOME_CAP<-factor(meta_data$OUTCOME_CAP, levels=c("n","y",".","Reference"),labels=c("No","Yes","No","Reference"))
  meta_data$OUTCOME_HCAP<-factor(meta_data$OUTCOME_HCAP, levels=c("n","y",".","Reference"),labels=c("No","Yes","No","Reference"))
  meta_data$OUTCOME_PSI<-factor(meta_data$OUTCOME_PSI, levels=c(".","1","2","3","4","Reference"),labels=c("Unknown","1","2","3","4","Reference"))
  meta_data$OUTCOME_COPD<-factor(meta_data$OUTCOME_COPD, levels=c("n","y",".","Reference"),labels=c("No","Yes","No","Reference"))
  meta_data$OUTCOME_Asthma<-factor(meta_data$OUTCOME_Asthma, levels=c("n","y",".","Reference"),labels=c("No","Yes","No","Reference"))
  meta_data$OUTCOME_Acute_Bronchitis<-factor(meta_data$OUTCOME_Acute_Bronchitis, levels=c("n","y",".","Reference"),labels=c("No","Yes","No","Reference"))
  meta_data$OUTCOME_Other.<-factor(meta_data$OUTCOME_Other., levels=c("n","y",".","Reference"),labels=c("No","Yes","No","Reference"))
  meta_data$Overall_Adverse_outcome<-factor(meta_data$Overall_Adverse_outcome, levels=c("n","y",".","Reference"),labels=c("No","Yes","No","Reference"))
  meta_data$Adverse_outcome_Death<-factor(meta_data$Adverse_outcome_Death, levels=c("n","y",".","Reference"),labels=c("No","Yes","No","Reference"))
  meta_data$Adverse_outcome_Endotracheal_Intubation<-factor(meta_data$Adverse_outcome_Endotracheal_Intubation, levels=c("n","y","Reference"),labels=c("No","Yes","Reference"))
  meta_data$Adverse_outcome_Vasopressors<-factor(meta_data$Adverse_outcome_Vasopressors, levels=c("n","y","Reference"),labels=c("No","Yes","Reference"))
  meta_data$Adverse_outcome_Renal_Failure<-factor(meta_data$Adverse_outcome_Renal_Failure, levels=c("n","y","Reference"),labels=c("No","Yes","Reference"))
  meta_data$Adverse_outcome_Lungabscess_Emphysema<-factor(meta_data$Adverse_outcome_Lungabscess_Emphysema, levels=c("n","y",".","Reference"),labels=c("No","Yes","NA","Reference"))
  meta_data$Adverse_outcome_Rehospitalization<-factor(meta_data$Adverse_outcome_Rehospitalization, levels=c("n","y",".","Reference"),labels=c("No","Yes","NA","Reference"))
  meta_data$Day_15_f_u_status<-factor(meta_data$Day_15_f_u_status)
  meta_data$day_15_AQ20_score<-as.numeric(meta_data$day_15_AQ20_score)
  meta_data$Day.30_f_u_satus<-as.numeric(meta_data$Day.30_f_u_satus)
  meta_data$Day.30_AQ20_score<-as.numeric(meta_data$Day.30_AQ20_score)
  meta_data$Hospital_d_c_Dispostion<-factor(meta_data$Hospital_d_c_Dispostion)
  meta_data$receive_abx<-factor(meta_data$receive_abx, levels=c("0","1"), labels=c("No","Yes"))
  meta_data$Day_15_f_u_status<-as.numeric(meta_data$Day_15_f_u_status)
  meta_data$sum_inhosp_duration<-as.numeric(meta_data$sum_inhosp_duration)
  meta_data$Adverse_outcome_Pneumonia_in_non_cap<-factor(meta_data$Adverse_outcome_Pneumonia_in_non_cap, levels=c("n","y","Reference"), labels=c("No","Yes","Reference"))
  meta_data$Hospital_d_c_date<-as.numeric(meta_data$Hospital_d_c_date)
  meta_data$sum_rehosp_duration<-as.numeric(meta_data$sum_rehosp_duration)
  meta_data$ED_steroids<-factor(meta_data$ED_steroids, levels=c("2","1",".","Reference"), labels=c("No","Yes","Not in ED","Reference"))
  meta_data$ED_bronchodilators<-factor(meta_data$ED_bronchodilators, levels=c("2","1",".","Reference"), labels=c("No","Yes","Not in ED","Reference"))
  meta_data$Corticosteroidsinhaled<-factor(meta_data$Corticosteroidsinhaled, levels=c("2","1","Reference"), labels=c("No","Yes","Reference"))
  meta_data$receive_abx<-gsub(0, "No",meta_data$receive_abx)
  meta_data$receive_abx<-gsub(1, "Yes",meta_data$receive_abx)
  meta_data$receive_abx<-factor(meta_data$receive_abx, levels=c("No","Yes","Reference"),labels=c("No","Yes","Reference"))
  #meta_data$receive_abx<-factor(meta_data$receive_abx, levels=c("No","Yes"),labels=c("No","Yes"))
  meta_data$abx_ed<-gsub(0,"No",meta_data$abx_ed)
  meta_data$abx_ed<-gsub(1,"Yes",meta_data$abx_ed)
  meta_data$abx_ed<-factor(meta_data$abx_ed, levels=c("No","Yes","Reference"),labels=c("No","Yes","Reference"))
  #meta_data$abx_ed<-factor(meta_data$abx_ed, levels=c("No","Yes","Reference"),labels=c("No","Yes"))
  meta_data$hosp_admit<-gsub(2,"No",meta_data$hosp_admit)
  meta_data$hosp_admit<-gsub(1,"Yes",meta_data$hosp_admit)
  meta_data$hosp_admit<-factor(meta_data$hosp_admit, levels=c("No","Yes",NA,"Reference"),labels=c("No","Yes","Reference"),exclude=NA)
  #meta_data$receive_abx<-factor(meta_data$receive_abx, levels=c("0","1"), labels=c("No","Yes"))
  #meta_data$abx_ed<-factor(meta_data$abx_ed, levels=c("0","1"), labels=c("No","Yes"),exclude=NA)
  meta_data$LRTIdecision<-factor(meta_data$LRTIdecision, levels=c("n","y","Reference"), labels=c("No","Yes","Reference"))
  meta_data$city<-factor(meta_data$city, levels=c("Reference","15","31","56","103","121","122"),labels=c("DRDR","Columbus","Pittsburgh","Hershey","Detroit","Detroit","Columbus"))
  return(meta_data)
}

sparserFactors<-function(x){
  logicvector<-as.vector("")
  metadata<-x
  #metadata<-metadata[,c(1:10,49,60,70)]
  Factorcols<-sapply(metadata, function(col) is.factor(col))
  tmp<-metadata[,Factorcols]
  print(tmp)
  for (i in 1:dim(tmp)[2]){
    #print(tmp[,i])
    print(colnames(tmp)[i])
    check<-tmp[,i]
    check<-as.vector(check)
    yeses<-grep ('Yes',check)
    nos<-grep('No',check)
    print(yeses)
    print(nos)
    ly<-length(yeses)
    ln<-length(nos)
    print(ly)
    print(ln)
    lx<-ly+ln
    nylx<-ly/lx
    lylx<-ln/lx
    print(nylx)
    print(lylx)
    if ((lylx>0.10&nylx>0.10&ly>5&ln>5)|colnames(tmp)[i]=="Batch"|colnames(tmp)[i]=="Sample_ID"){
      print("GOOD")
      STATUS<-TRUE
    }else{
      print("BAD")
      STATUS<-FALSE
    }
    logicvector[i]<-STATUS
  }
  names(logicvector)<-colnames(tmp)
  print (logicvector)
  logicvector<-as.logical(logicvector)
  parsed<-tmp[,logicvector]
  return(parsed)
}